/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Fachada.Fachada;

/**
 *
 * @author Darwin
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private static Fachada modelo=null;
    
    public Principal() {
        initComponents();
        modelo=Fachada.getInstancia();
        this.CargarConfiguracionInicial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnusuarios = new javax.swing.JButton();
        btntarjetas = new javax.swing.JButton();
        btninformes = new javax.swing.JButton();
        btncfg = new javax.swing.JButton();
        btnmonitor = new javax.swing.JButton();
        btnsectores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnusuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario_ico.png"))); // NOI18N
        btnusuarios.setText("Usuarios");
        btnusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusuariosActionPerformed(evt);
            }
        });

        btntarjetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/UsuariosRegistro.GIF"))); // NOI18N
        btntarjetas.setText("Tarjetas");
        btntarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntarjetasActionPerformed(evt);
            }
        });

        btninformes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Estadistica y probabilidad.gif"))); // NOI18N
        btninformes.setText("Informes");
        btninformes.setPreferredSize(new java.awt.Dimension(99, 23));
        btninformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninformesActionPerformed(evt);
            }
        });

        btncfg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/config.gif"))); // NOI18N
        btncfg.setText("Configuración");
        btncfg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncfgActionPerformed(evt);
            }
        });

        btnmonitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/monitoreo.jpg"))); // NOI18N
        btnmonitor.setText("Monitor");
        btnmonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmonitorActionPerformed(evt);
            }
        });

        btnsectores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sector_ico.png"))); // NOI18N
        btnsectores.setText("Sectores");
        btnsectores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsectoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btninformes, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncfg, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnmonitor, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnusuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsectores)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnmonitor, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btntarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnsectores, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 212, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btncfg, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btninformes, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncfgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncfgActionPerformed
        Configuracion();
    }//GEN-LAST:event_btncfgActionPerformed

    private void btnusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusuariosActionPerformed
        this.Usuarios();
    }//GEN-LAST:event_btnusuariosActionPerformed

    private void btntarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntarjetasActionPerformed
        this.Tarjetas();
    }//GEN-LAST:event_btntarjetasActionPerformed

    private void btnsectoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsectoresActionPerformed
        this.Sectores();
    }//GEN-LAST:event_btnsectoresActionPerformed

    private void btninformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninformesActionPerformed
        this.Registros();
    }//GEN-LAST:event_btninformesActionPerformed

    private void btnmonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmonitorActionPerformed
        this.Monitor();
    }//GEN-LAST:event_btnmonitorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncfg;
    private javax.swing.JButton btninformes;
    private javax.swing.JButton btnmonitor;
    private javax.swing.JButton btnsectores;
    private javax.swing.JButton btntarjetas;
    private javax.swing.JButton btnusuarios;
    // End of variables declaration//GEN-END:variables


    private void Usuarios(){
        Usuarios u=new Usuarios();
        u.setVisible(true);
    }
    
    private void Tarjetas(){
        Tarjetas t=new Tarjetas();
        t.setVisible(true);
    }
    
    private void Registros(){
        Registros r=new Registros();
        r.setVisible(true);
    }
    
    private void Sectores(){
        Sectores s=new Sectores();
        s.setVisible(true);
    }
    
    private void Monitor(){
        Monitor m=new Monitor();
        m.setVisible(true);
    }
    
    private void Configuracion(){
    Configuracion cfp=new Configuracion();
    cfp.setVisible(true);
    }

    private void CargarConfiguracionInicial(){
    modelo.Inicio();
    }

}

