/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Fachada.Fachada;
import Modelo.Tarjeta;
import Modelo.Usuario;

/**
 *
 * @author Darwin
 */
public class Tarjetas extends javax.swing.JFrame {

    private Fachada modelo;
    /**
     * Creates new form Tarjetas
     */
    public Tarjetas() {
        initComponents();
        this.modelo=Fachada.getInstancia();
        this.CargarListadoTarjetas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lsttarjetas = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        btnagregar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        txtnrotarjeta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnombreusuario = new javax.swing.JTextField();
        btncerrar = new javax.swing.JButton();
        btntarjetaslibres = new javax.swing.JButton();
        btntarjetastodas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lsttarjetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lsttarjetasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lsttarjetas);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Tarjetas");

        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        txtnrotarjeta.setEditable(false);

        jLabel2.setText("Numero:");

        jLabel3.setText("Asignada a:");

        txtnombreusuario.setEditable(false);
        txtnombreusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnombreusuarioMouseClicked(evt);
            }
        });

        btncerrar.setText("Cerrar");
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });

        btntarjetaslibres.setText("Cargar tarjetas libres");
        btntarjetaslibres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntarjetaslibresActionPerformed(evt);
            }
        });

        btntarjetastodas.setText("Cargar todas");
        btntarjetastodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntarjetastodasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtnombreusuario))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtnrotarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnagregar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnmodificar)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btncerrar)
                                            .addComponent(btneliminar)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btntarjetastodas, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btntarjetaslibres, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtnrotarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtnombreusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnagregar)
                            .addComponent(btnmodificar)
                            .addComponent(btneliminar))
                        .addGap(35, 35, 35)
                        .addComponent(btntarjetaslibres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btntarjetastodas)
                            .addComponent(btncerrar)))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombreusuarioMouseClicked
        this.VerUsuarioAsignado();
    }//GEN-LAST:event_txtnombreusuarioMouseClicked

    private void lsttarjetasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lsttarjetasMouseClicked
        this.CargarTarjetaSeleccionada();
    }//GEN-LAST:event_lsttarjetasMouseClicked

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        this.Add();
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        this.Update();
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        this.Delete();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        this.Cerrar();
    }//GEN-LAST:event_btncerrarActionPerformed

    private void btntarjetaslibresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntarjetaslibresActionPerformed
        this.CargarListadoTarjetasLibres();
    }//GEN-LAST:event_btntarjetaslibresActionPerformed

    private void btntarjetastodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntarjetastodasActionPerformed
        this.CargarListadoTarjetas();
    }//GEN-LAST:event_btntarjetastodasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tarjetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tarjetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btntarjetaslibres;
    private javax.swing.JButton btntarjetastodas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lsttarjetas;
    private javax.swing.JTextField txtnombreusuario;
    private javax.swing.JTextField txtnrotarjeta;
    // End of variables declaration//GEN-END:variables

    private void VerUsuarioAsignado(){
        if(!this.lsttarjetas.isSelectionEmpty()&&!this.txtnombreusuario.getText().trim().isEmpty()){
            Tarjeta t=(Tarjeta) this.lsttarjetas.getModel().getElementAt(this.lsttarjetas.getSelectedIndex());
            FichaUsuario fu=new FichaUsuario(this,true);
            fu.CargarDatosUsuario(modelo.GetUsuarioByTarjeta(t));
            fu.setVisible(true);
        }
    }
    
    private void Add(){
        TarjetaABM tABM=new TarjetaABM(this,true);
        tABM.setTitulo("Agregar tarjeta");
        tABM.setVisible(true);
        this.CargarListadoTarjetas();
    }
    
    private void Update(){
        if(!this.lsttarjetas.isSelectionEmpty()){
            Tarjeta t=(Tarjeta) this.lsttarjetas.getModel().getElementAt(this.lsttarjetas.getSelectedIndex());
            TarjetaABM tABM=new TarjetaABM(this,true);
            tABM.setTarjeta(t);
            tABM.setTitulo("Modificar tarjeta");
            tABM.setVisible(true);
            this.CargarListadoTarjetas();
        }
    }
    
    private void Delete(){
        if(!this.lsttarjetas.isSelectionEmpty()){
            Tarjeta t=(Tarjeta) this.lsttarjetas.getModel().getElementAt(this.lsttarjetas.getSelectedIndex());
            this.modelo.BorraTarjeta(t.id());
            this.CargarListadoTarjetas();
        }
    }
    
    private void CargarTarjetaSeleccionada(){
        this.LimpiarCampos();
        if(!this.lsttarjetas.isSelectionEmpty()){
            Tarjeta t=(Tarjeta) this.lsttarjetas.getModel().getElementAt(this.lsttarjetas.getSelectedIndex());
            Usuario u=modelo.GetUsuarioByTarjeta(t);
            if(u!=null)this.txtnombreusuario.setText(u.nombre());
            this.txtnrotarjeta.setText(t.codigo());
        }
    }
    
    private void LimpiarCampos(){
        this.txtnombreusuario.setText(null);
        this.txtnrotarjeta.setText(null);
    }
    
    private void CargarListadoTarjetas(){
        this.lsttarjetas.setModel(this.modelo.getListadoTarjetas());
    }
    
    private void CargarListadoTarjetasLibres(){
        this.lsttarjetas.setModel(this.modelo.GetListadoTarjetasLibres());
    }
    
    private void Cerrar(){
        this.setVisible(false);
    }
}
